# Generated by Django 2.1.2 on 2019-12-30 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='mobiel',
            new_name='mobile',
        ),
    ]
